# Generated by Django 2.2.4 on 2021-02-19 11:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Enter Your Name')),
                ('profile', models.CharField(max_length=100, verbose_name='Enter Your Profile')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Enter Your E-mail')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Enter Your Phone')),
                ('description', models.TextField(max_length=600, verbose_name='About You ')),
                ('image', models.ImageField(upload_to='about', verbose_name='Upload Image')),
                ('skill', multiselectfield.db.fields.MultiSelectField(choices=[('HTML', 'HTML'), ('Python', 'PYTHON'), ('Django', 'DJANGO'), ('Javascript', 'Js'), ('SQL', 'Mysql')], max_length=33, verbose_name='Skills ')),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service Title')),
                ('description', models.TextField(max_length=600, verbose_name='Service Description')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Work Title')),
                ('image', models.ImageField(upload_to='work', verbose_name='Upload Image')),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=600, verbose_name='Work Description')),
            ],
            options={
                'db_table': 'work',
            },
        ),
    ]
